baseURL = 'https://example.org/'
title = 'Hugoplate'
timeZone = 'America/New_York'
summaryLength = 10.0
disableLanguages = [
]
hasCJKLanguage = false
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
params.plugins.css = [
	{ link = 'plugins/swiper/swiper-bundle.css', lazy = true },
	{ link = 'plugins/glightbox/glightbox.css', lazy = true },
	{ link = 'plugins/font-awesome/v6/brands.css', lazy = true },
	{ link = 'plugins/font-awesome/v6/solid.css', lazy = true },
	{ link = 'plugins/font-awesome/v6/icons.css', lazy = true },
]
params.plugins.js = [
	{ link = 'js/search.js', lazy = false },
	{ link = 'plugins/swiper/swiper-bundle.js', lazy = false },
	{ link = 'plugins/glightbox/glightbox.js', lazy = true },
	{ link = 'js/gallery-slider.js', lazy = true },
	{ link = 'plugins/cookie.js', lazy = false },
	{ link = 'js/accordion.js', lazy = true },
	{ link = 'js/tab.js', lazy = true },
	{ link = 'js/modal.js', lazy = true },
	{ link = 'plugins/youtube-lite.js', lazy = true },
]

[services]

[services.googleAnalytics]

ID = 'G-MEASUREMENT_ID'

[services.disqus]

shortname = 'themefisher-template'

[permalinks.page]

pages = '/:slugorcontentbasename/'

[pagination]

disableAliases = false
pagerSize = 10.0
path = 'page'

[build]

cachebusters = [
	{ source = 'assets/notwatching/hugo_stats\.json', target = 'css' },
]

[build.buildStats]

enable = true

[module]

mounts = [
	{ source = 'assets', target = 'assets' },
	{ disableWatch = true, source = 'hugo_stats.json', target = 'assets/notwatching/hugo_stats.json' },
]

[outputs]

home = [
	'HTML',
	'RSS',
	'WebAppManifest',
	'SearchIndex',
]

[imaging]

quality = 80.0
resampleFilter = 'Lanczos'

[caches]

[caches.images]

dir = ':resourceDir/_gen'
maxAge = '720h'

[caches.assets]

dir = ':resourceDir/_gen'
maxAge = '720h'

[markup]

[markup.goldmark.renderer]

unsafe = true

[markup.highlight]

style = 'monokai'
lineNumbersInTable = false

[markup.tableOfContents]

startLevel = 2.0
endLevel = 5.0
ordered = true

[mediaTypes]

[mediaTypes.'application/manifest+json']

suffixes = [
	'webmanifest',
]

[outputFormats]

[outputFormats.WebAppManifest]

mediaType = 'application/manifest+json'
rel = 'manifest'

[outputFormats.SearchIndex]

mediaType = 'application/json'
baseName = 'searchindex'
isPlainText = true
notAlternative = true
